{% macro create_bronze_tables() %}

    {% set create_ad_table %}

        CREATE TABLE IF NOT EXISTS
            {{ target.database }}.BRONZE.HYROS_AD_ATTRIBUTION_RAW
        (
            AD_ID VARCHAR,
            AD_NAME VARCHAR,
            ADSET_NAME VARCHAR,
            PLATFORM VARCHAR,
            LEVEL VARCHAR,
            START_DATE VARCHAR,
            END_DATE VARCHAR,

            FIRST_SOURCE_CLICK_ID VARCHAR,
            FIRST_SOURCE_CLICK_NAME VARCHAR,
            FIRST_SOURCE_LEADS VARCHAR,
            FIRST_SOURCE_NEW_LEADS VARCHAR,
            FIRST_SOURCE_CALLS VARCHAR,
            FIRST_SOURCE_QUALIFIED_CALLS VARCHAR,
            FIRST_SOURCE_SALES VARCHAR,
            FIRST_SOURCE_REVENUE VARCHAR,
            FIRST_SOURCE_RECURRING_REVENUE VARCHAR,
            FIRST_SOURCE_TOTAL_REVENUE VARCHAR,
            FIRST_SOURCE_PROFIT VARCHAR,
            FIRST_SOURCE_COST VARCHAR,
            FIRST_SOURCE_ROI VARCHAR,
            FIRST_SOURCE_ROAS VARCHAR,
            FIRST_SOURCE_CLICKS VARCHAR,
            FIRST_SOURCE_IMPRESSIONS VARCHAR,
            FIRST_SOURCE_CTR VARCHAR,
            FIRST_SOURCE_CPM VARCHAR,
            FIRST_SOURCE_CVR VARCHAR,
            FIRST_SOURCE_COST_PER_LEAD VARCHAR,
            FIRST_SOURCE_COST_PER_CLICK VARCHAR,
            FIRST_SOURCE_COST_PER_CALL VARCHAR,

            LAST_SOURCE_CLICK_ID VARCHAR,
            LAST_SOURCE_CLICK_NAME VARCHAR,
            LAST_SOURCE_LEADS VARCHAR,
            LAST_SOURCE_NEW_LEADS VARCHAR,
            LAST_SOURCE_CALLS VARCHAR,
            LAST_SOURCE_QUALIFIED_CALLS VARCHAR,
            LAST_SOURCE_SALES VARCHAR,
            LAST_SOURCE_REVENUE VARCHAR,
            LAST_SOURCE_RECURRING_REVENUE VARCHAR,
            LAST_SOURCE_TOTAL_REVENUE VARCHAR,
            LAST_SOURCE_PROFIT VARCHAR,
            LAST_SOURCE_COST VARCHAR,
            LAST_SOURCE_ROI VARCHAR,
            LAST_SOURCE_ROAS VARCHAR,
            LAST_SOURCE_CLICKS VARCHAR,
            LAST_SOURCE_IMPRESSIONS VARCHAR,
            LAST_SOURCE_CTR VARCHAR,
            LAST_SOURCE_CPM VARCHAR,
            LAST_SOURCE_CVR VARCHAR,
            LAST_SOURCE_COST_PER_LEAD VARCHAR,
            LAST_SOURCE_COST_PER_CLICK VARCHAR,
            LAST_SOURCE_COST_PER_CALL VARCHAR,

            SCIENTIFIC_SOURCE_CLICK_ID VARCHAR,
            SCIENTIFIC_SOURCE_CLICK_NAME VARCHAR,
            SCIENTIFIC_SOURCE_LEADS VARCHAR,
            SCIENTIFIC_SOURCE_NEW_LEADS VARCHAR,
            SCIENTIFIC_SOURCE_CALLS VARCHAR,
            SCIENTIFIC_SOURCE_QUALIFIED_CALLS VARCHAR,
            SCIENTIFIC_SOURCE_SALES VARCHAR,
            SCIENTIFIC_SOURCE_REVENUE VARCHAR,
            SCIENTIFIC_SOURCE_RECURRING_REVENUE VARCHAR,
            SCIENTIFIC_SOURCE_TOTAL_REVENUE VARCHAR,
            SCIENTIFIC_SOURCE_PROFIT VARCHAR,
            SCIENTIFIC_SOURCE_COST VARCHAR,
            SCIENTIFIC_SOURCE_ROI VARCHAR,
            SCIENTIFIC_SOURCE_ROAS VARCHAR,
            SCIENTIFIC_SOURCE_CLICKS VARCHAR,
            SCIENTIFIC_SOURCE_IMPRESSIONS VARCHAR,
            SCIENTIFIC_SOURCE_CTR VARCHAR,
            SCIENTIFIC_SOURCE_CPM VARCHAR,
            SCIENTIFIC_SOURCE_CVR VARCHAR,
            SCIENTIFIC_SOURCE_COST_PER_LEAD VARCHAR,
            SCIENTIFIC_SOURCE_COST_PER_CLICK VARCHAR,
            SCIENTIFIC_SOURCE_COST_PER_CALL VARCHAR,

            MD5_HASH VARCHAR,
            INSERT_DATE VARCHAR,
            UPDATE_DATE VARCHAR,

            SOURCE_FILE_NAME VARCHAR,
            SOURCE_FILE_ROW_NUMBER NUMBER,
            SOURCE_FILE_LAST_MODIFIED TIMESTAMP_TZ,
            LOAD_TIMESTAMP TIMESTAMP_TZ
        )

    {% endset %}


    {% set create_leads_table %}

        CREATE TABLE IF NOT EXISTS
            {{ target.database }}.BRONZE.HYROS_LEADS_RAW
        (
            LEAD_ID VARCHAR,
            CREATED_DATE VARCHAR,

            FIRST_SOURCE_CLICK_DATE VARCHAR,
            FIRST_SOURCE_AD_ACCOUNT_ID VARCHAR,
            FIRST_SOURCE_ADSET_ID VARCHAR,
            FIRST_SOURCE_PLATFORM_NAME VARCHAR,
            FIRST_SOURCE_CAMPAIGN_ID VARCHAR,
            FIRST_SOURCE_CAMPAIGN_NAME VARCHAR,
            FIRST_SOURCE_TRAFFIC_ID VARCHAR,
            FIRST_SOURCE_TRAFFIC_NAME VARCHAR,
            FIRST_SOURCE_ADSET VARCHAR,
            FIRST_SOURCE_AD_NAME VARCHAR,
            FIRST_SOURCE_AD_ID VARCHAR,

            LAST_SOURCE_CLICK_DATE VARCHAR,
            LAST_SOURCE_AD_ACCOUNT_ID VARCHAR,
            LAST_SOURCE_ADSET_ID VARCHAR,
            LAST_SOURCE_PLATFORM_NAME VARCHAR,
            LAST_SOURCE_CAMPAIGN_ID VARCHAR,
            LAST_SOURCE_CAMPAIGN_NAME VARCHAR,
            LAST_SOURCE_TRAFFIC_ID VARCHAR,
            LAST_SOURCE_TRAFFIC_NAME VARCHAR,
            LAST_SOURCE_ADSET VARCHAR,
            LAST_SOURCE_AD_NAME VARCHAR,
            LAST_SOURCE_AD_ID VARCHAR,

            MD5_HASH VARCHAR,
            INSERT_DATE VARCHAR,
            UPDATE_DATE VARCHAR,

            SOURCE_FILE_NAME VARCHAR,
            SOURCE_FILE_ROW_NUMBER NUMBER,
            SOURCE_FILE_LAST_MODIFIED TIMESTAMP_TZ,
            LOAD_TIMESTAMP TIMESTAMP_TZ
        )

    {% endset %}


    {% set create_inbound_table %}

        CREATE TABLE IF NOT EXISTS
            {{ target.database }}.BRONZE.MARKETING_INBOUND_CAMPAIGN_RAW
        (
            FIRST_SOURCE_CALENDLY_CAMPAIGN VARCHAR,
            FIRST_SOURCE VARCHAR,
            LAST_SOURCE_CALENDLY_CAMPAIGN VARCHAR,
            LAST_SOURCE VARCHAR,
            ACTIVITY_LOG_DATE VARCHAR,
            STATUS VARCHAR,
            TRIAGE_CALL_DATE VARCHAR,
            TRIAGE_YEAR_WEEK VARCHAR,
            LEAD_ID VARCHAR,
            TAKEN_STATUS VARCHAR,
            STRATEGY_CALL_STATUS VARCHAR,
            STRATEGY_CALL_TAKEN_STATUS VARCHAR,
            SALE_STATUS VARCHAR,
            CONTRACTED_VALUE VARCHAR,
            SOURCE_FILE_NAME VARCHAR,
            SOURCE_FILE_ROW_NUMBER NUMBER,
            SOURCE_FILE_LAST_MODIFIED TIMESTAMP_TZ,
            LOAD_TIMESTAMP TIMESTAMP_TZ
        )

    {% endset %}


    {% if execute %}

        {{ log("Creating Bronze tables...", info=True) }}

        {% do run_query(create_ad_table) %}
        {% do run_query(create_leads_table) %}
        {% do run_query(create_inbound_table) %}

        {{ log("Bronze tables are ready.", info=True) }}

    {% endif %}

{% endmacro %}