USE ROLE ACCOUNTADMIN;
-- Create the project database
CREATE DATABASE IF NOT EXISTS MARKETING_ANALYTICS_DB;

-- Create Medallion Architecture schemas
CREATE SCHEMA IF NOT EXISTS MARKETING_ANALYTICS_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS MARKETING_ANALYTICS_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS MARKETING_ANALYTICS_DB.GOLD;

-- Create a small warehouse for project processing
CREATE WAREHOUSE IF NOT EXISTS MARKETING_ANALYTICS_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;





