USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS MARKETING_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS MARKETING_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS MARKETING_ANALYTICS.BRONZE;
CREATE SCHEMA IF NOT EXISTS MARKETING_ANALYTICS.SILVER;
CREATE SCHEMA IF NOT EXISTS MARKETING_ANALYTICS.GOLD;
CREATE SCHEMA IF NOT EXISTS MARKETING_ANALYTICS.CONTROL;

USE WAREHOUSE MARKETING_WH;
USE DATABASE MARKETING_ANALYTICS;