USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION MARKETING_S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN =
        'arn:aws:iam::277894851352:role/snowflake-marketing-s3-role'
    STORAGE_ALLOWED_LOCATIONS = (
        's3://marketingdata234/data/daily/'
    );

DESC INTEGRATION MARKETING_S3_INT;