USE DATABASE MARKETING_ANALYTICS;
USE SCHEMA BRONZE;

CREATE OR REPLACE FILE FORMAT MARKETING_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL', 'null')
    TRIM_SPACE = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    REPLACE_INVALID_CHARACTERS = TRUE;