USE DATABASE MARKETING_ANALYTICS;
USE SCHEMA BRONZE;

CREATE OR REPLACE STAGE STG_HYROS_AD_ATTRIBUTION
    URL = 's3://marketingdata234/data/daily/hyros_ad_attribution/'
    STORAGE_INTEGRATION = MARKETING_S3_INT
    FILE_FORMAT = MARKETING_CSV_FORMAT;

CREATE OR REPLACE STAGE STG_HYROS_LEADS
    URL = 's3://marketingdata234/data/daily/hyros_leads/'
    STORAGE_INTEGRATION = MARKETING_S3_INT
    FILE_FORMAT = MARKETING_CSV_FORMAT;

CREATE OR REPLACE STAGE STG_MARKETING_INBOUND_CAMPAIGN
    URL = 's3://marketingdata234/data/daily/marketing_inbound_campaign/'
    STORAGE_INTEGRATION = MARKETING_S3_INT
    FILE_FORMAT = MARKETING_CSV_FORMAT;

LIST @STG_HYROS_AD_ATTRIBUTION;
LIST @STG_HYROS_LEADS;
LIST @STG_MARKETING_INBOUND_CAMPAIGN;