CREATE OR REPLACE STAGE MARKETING_ANALYTICS_DB.BRONZE.MARKETING_S3_STAGE
    URL = 's3://marketing-analytics-project-7days/marketing-data/'
    STORAGE_INTEGRATION = MARKETING_S3_INT
    FILE_FORMAT = MARKETING_ANALYTICS_DB.BRONZE.MARKETING_CSV_FORMAT;

list @MARKETING_ANALYTICS_DB.BRONZE.MARKETING_S3_STAGE;