USE ROLE ACCOUNTADMIN;
USE WAREHOUSE MARKETING_WH;
USE DATABASE MARKETING_ANALYTICS;
USE SCHEMA CONTROL;

CREATE OR REPLACE TASK TASK_LOAD_BRONZE_DAILY
    WAREHOUSE = MARKETING_WH
    SCHEDULE = 'USING CRON 0 8 * * * America/New_York'
AS
    CALL MARKETING_ANALYTICS.CONTROL.SP_LOAD_BRONZE();

ALTER TASK MARKETING_ANALYTICS.CONTROL.TASK_LOAD_BRONZE_DAILY RESUME;

SHOW TASKS LIKE 'TASK_LOAD_BRONZE_DAILY'
IN SCHEMA MARKETING_ANALYTICS.CONTROL;

EXECUTE TASK MARKETING_ANALYTICS.CONTROL.TASK_LOAD_BRONZE_DAILY;

SELECT
    NAME,
    STATE,
    SCHEDULED_TIME,
    COMPLETED_TIME,
    ERROR_CODE,
    ERROR_MESSAGE
FROM TABLE(
    MARKETING_ANALYTICS.INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'TASK_LOAD_BRONZE_DAILY',
        RESULT_LIMIT => 10
    )
)
ORDER BY SCHEDULED_TIME DESC;

SELECT
    'HYROS_AD_ATTRIBUTION_RAW' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT
FROM MARKETING_ANALYTICS.BRONZE.HYROS_AD_ATTRIBUTION_RAW

UNION ALL

SELECT
    'HYROS_LEADS_RAW',
    COUNT(*)
FROM MARKETING_ANALYTICS.BRONZE.HYROS_LEADS_RAW

UNION ALL

SELECT
    'MARKETING_INBOUND_CAMPAIGN_RAW',
    COUNT(*)
FROM MARKETING_ANALYTICS.BRONZE.MARKETING_INBOUND_CAMPAIGN_RAW;