name: "dbt_marketing_analytics"
version: "1.0.0"
config-version: 2

profile: "dbt_marketing_analytics"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_marketing_analytics:

    silver:
      +schema: SILVER
      +materialized: incremental
      +incremental_strategy: merge

    gold:
      +schema: GOLD
      +materialized: table